Name: Adarsh Sapkota

Student ID: 2407043


In [ ]:
import sys

if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Python version is compatible")
    print(sys.version)
else:
    print("Please use Python 3.6 or higher")

Python version is compatible
3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
# Mutable (List)
my_list = [1, 2, 3]
my_list.append(4)
print("Modified List:", my_list)

# Immutable (Tuple)
my_tuple = (1, 2, 3)
print("Tuple:", my_tuple)

Modified List: [1, 2, 3, 4]
Tuple: (1, 2, 3)


In [ ]:
num = -2

if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Negative


In [ ]:
# For loop
for i in range(5):
    print(i)

# While loop
count = 0
while count < 3:
    print("Count:", count)
    count += 1

0
1
2
3
4
Count: 0
Count: 1
Count: 2


In [ ]:
def add_numbers(a, b):
    """
    Adds two numbers.
    Returns their sum.
    """
    return a + b

print(add_numbers(5, 76))

81


In [ ]:
try:
    x = int(input("Enter a number: "))
    print(10 / x)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid input.")

Enter a number: 5
2.0


In [ ]:
import numpy as np

In [ ]:
import numpy as np
# Zero array
zeros_arr = np.zeros((2,3))
print(zeros_arr)

# Ones array
ones_arr = np.ones((3,2))
print(ones_arr)

# Identity matrix
identity = np.eye(3)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [ ]:
arr = np.arange(6)
reshaped = arr.reshape(2,3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


SECTION 3: ARRAY INDEXING & SLICING
  

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0,1])        # Single element
print(arr[:,1])        # Column slice
print(arr[0:2,1:3])    # Sub-matrix

2
[2 5 8]
[[2 3]
 [5 6]]


SECTION 4: ARRAY MATHEMATICS

In [ ]:
arr = np.array([1,4,9,16])

print("Square:", np.square(arr))
print("Square Root:", np.sqrt(arr))
print("Log:", np.log(arr))

Square: [  1  16  81 256]
Square Root: [1. 2. 3. 4.]
Log: [0.         1.38629436 2.19722458 2.77258872]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Dot Product:\n", np.dot(A,B))
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

Dot Product:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


SECTION 5: BROADCASTING

In [ ]:
A = np.array([[1],[2],[3]])
B = np.array([10,20,30])

C = A + B
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


SECTION 6: VECTORIZATION (WHY NUMPY IS FAST)

In [ ]:
import time

size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Loop method
start = time.time()
result = np.zeros(size)
for i in range(size):
    result[i] = a[i] + b[i]
end = time.time()
print("Loop Time:", end - start)

# Vectorized
start = time.time()
result2 = a + b
end = time.time()
print("Vectorized Time:", end - start)

Loop Time: 0.47464513778686523
Vectorized Time: 0.008038520812988281


SECTION 7: CONNECTION TO MACHINE LEARNING

In [ ]:
# Simple Gradient Descent Example

# Data
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

# Initialize weight
w = 0.0
learning_rate = 0.01

# Training
for epoch in range(100):
    y_pred = w * x
    loss = np.mean((y - y_pred)**2)

    # derivative
    dw = -2 * np.mean(x * (y - y_pred))

    w = w - learning_rate * dw

print("Final Weight:", w)

Final Weight: 1.9999998250465274


**WHY DERIVATIVE IS USED IN ML & DL**


Every model is guided by a loss function that needs to be minimized. Derivatives indicate how the loss changes with respect to parameters, providing a direction for adjustment. Gradient descent uses this information to update the parameters iteratively, while backpropagation applies the chain rule to efficiently compute these derivatives across layers. Without derivatives, neural networks lose the ability to learn, and optimization cannot be carried out.